exports.seed = (knex) => {
  // Deletes ALL existing entries
  return knex('districts')
    .del()
    .then(() => {
      // Inserts seed entries
      return knex('districts').insert([
        {
          regionCode: 'AUK',
          code: 'ALC',
          name: 'Auckland City',
        },
        { regionCode: 'AUK', code: 'FRK', name: 'Franklin' },
        {
          regionCode: 'AUK',
          code: 'HGI',
          name: 'Hauraki Gulf Island',
        },
        {
          regionCode: 'AUK',
          code: 'MKC',
          name: 'Manukau City',
        },
        {
          regionCode: 'AUK',
          code: 'NSC',
          name: 'North Shore City',
        },
        { regionCode: 'AUK', code: 'PPK', name: 'Papakura' },
        { regionCode: 'AUK', code: 'RDN', name: 'Rodney' },
        {
          regionCode: 'AUK',
          code: 'WHI',
          name: 'Waiheke Island',
        },
        {
          regionCode: 'AUK',
          code: 'WKC',
          name: 'Waitakere City',
        },
        { regionCode: 'WKO', code: 'HMT', name: 'Hamilton' },
        { regionCode: 'WKO', code: 'HRK', name: 'Hauraki' },
        {
          regionCode: 'WKO',
          code: 'MMP',
          name: 'Matamata-Piako',
        },
        { regionCode: 'WKO', code: 'OTH', name: 'Otorohanga' },
        {
          regionCode: 'WKO',
          code: 'SWK',
          name: 'South Waikato',
        },
        { regionCode: 'WKO', code: 'TUP', name: 'Taupo' },
        {
          regionCode: 'WKO',
          code: 'TCD',
          name: 'Thames-Coromandel',
        },
        { regionCode: 'WKO', code: 'WIK', name: 'Waikato' },
        { regionCode: 'WKO', code: 'WIP', name: 'Waipa' },
        { regionCode: 'WKO', code: 'WTM', name: 'Waitomo' },
        { regionCode: 'BOP', code: 'KWR', name: 'Kawerau' },
        { regionCode: 'BOP', code: 'OTK', name: 'Opotiki' },
        { regionCode: 'BOP', code: 'RTR', name: 'Rotorua' },
        { regionCode: 'BOP', code: 'TRA', name: 'Tauranga' },
        {
          regionCode: 'BOP',
          code: 'WBP',
          name: 'Western Bay Of Plenty',
        },
        { regionCode: 'BOP', code: 'WKT', name: 'Whakatane' },
        {
          regionCode: 'TKI',
          code: 'NPM',
          name: 'New Plymouth',
        },
        {
          regionCode: 'TKI',
          code: 'STK',
          name: 'South Taranaki',
        },
        { regionCode: 'TKI', code: 'STF', name: 'Stratford' },
        { regionCode: 'MWT', code: 'HWA', name: 'Horowhenua' },
        { regionCode: 'MWT', code: 'MWT', name: 'Manawatu' },
        {
          regionCode: 'MWT',
          code: 'PSN',
          name: 'Palmerston North',
        },
        { regionCode: 'MWT', code: 'RTK', name: 'Rangitikei' },
        { regionCode: 'MWT', code: 'RPH', name: 'Ruapehu' },
        { regionCode: 'MWT', code: 'TRU', name: 'Taraua' },
        { regionCode: 'MWT', code: 'WHN', name: 'Whanganui' },
        { regionCode: 'WGN', code: 'CTT', name: 'Carterton' },
        {
          regionCode: 'WGN',
          code: 'KTC',
          name: 'Kapiti Coast',
        },
        { regionCode: 'WGN', code: 'LHT', name: 'Lower Hutt' },
        { regionCode: 'WGN', code: 'MTT', name: 'Masterton' },
        { regionCode: 'WGN', code: 'PRR', name: 'Porirua' },
        {
          regionCode: 'WGN',
          code: 'SWP',
          name: 'South Wairarapa',
        },
        { regionCode: 'WGN', code: 'UHT', name: 'Upper Hutt' },
        { regionCode: 'WGN', code: 'WGT', name: 'Wellington' },
        { regionCode: 'NSN', code: 'NSN', name: 'Nelson' },
        { regionCode: 'NSN', code: 'TSM', name: 'Tasman' },
        { regionCode: 'MBH', code: 'BHM', name: 'Blenheim' },
        { regionCode: 'MBH', code: 'KKR', name: 'Kaikoura' },
        { regionCode: 'MBH', code: 'MBR', name: 'Marlborough' },
        { regionCode: 'WTC', code: 'BLR', name: 'Buller' },
        { regionCode: 'WTC', code: 'GRY', name: 'Grey' },
        { regionCode: 'WTC', code: 'WTL', name: 'Westland' },
        { regionCode: 'CAN', code: 'ABT', name: 'Ashburton' },
        {
          regionCode: 'CAN',
          code: 'BPL',
          name: 'Banks Peninsula',
        },
        {
          regionCode: 'CAN',
          code: 'CCC',
          name: 'Christchurch City',
        },
        { regionCode: 'CAN', code: 'HRN', name: 'Hurunui' },
        { regionCode: 'CAN', code: 'MKZ', name: 'Mackenzie' },
        { regionCode: 'CAN', code: 'SLW', name: 'Selwyn' },
        { regionCode: 'CAN', code: 'TMR', name: 'Timaru' },
        { regionCode: 'CAN', code: 'WKR', name: 'Waimakariri' },
        { regionCode: 'CAN', code: 'WMT', name: 'Waimate' },
        {
          regionCode: 'OTA',
          code: 'OTG',
          name: 'Central Otago',
        },
        { regionCode: 'OTA', code: 'CLT', name: 'Clutha' },
        { regionCode: 'OTA', code: 'DND', name: 'Dunedin' },
        {
          regionCode: 'OTA',
          code: 'QTL',
          name: 'Queenstown-Lakes',
        },
        { regionCode: 'OTA', code: 'SOT', name: 'South Otago' },
        { regionCode: 'OTA', code: 'WNK', name: 'Wanaka' },
        { regionCode: 'STL', code: 'CLN', name: 'Catlins' },
        { regionCode: 'STL', code: 'GRE', name: 'Gore' },
        {
          regionCode: 'STL',
          code: 'ICG',
          name: 'Invercargill',
        },
        { regionCode: 'STL', code: 'STL', name: 'Southland' },
      ])
    })
}
