exports.seed = (knex) => {
  // Deletes ALL existing entries
  return knex('districts')
    .del()
    .then(() => {
      // Inserts seed entries
      return knex('districts').insert([
        {
          regionCode: 'AUK',
          code: 'ALC',
          name: 'Auckland City',
          weatherLocName: 'auckland',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'AUK',
          code: 'FRK',
          name: 'Franklin',
          weatherLocName: 'auckland',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'AUK',
          code: 'HGI',
          name: 'Hauraki Gulf Island',
          weatherLocName: 'auckland',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'AUK',
          code: 'MKC',
          name: 'Manukau City',
          weatherLocName: 'manukau',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'AUK',
          code: 'NSC',
          name: 'North Shore City',
          weatherLocName: 'north-shore',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'AUK',
          code: 'PPK',
          name: 'Papakura',
          weatherLocName: 'hunua',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'AUK',
          code: 'RDN',
          name: 'Rodney',
          weatherLocName: 'warkworth',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'AUK',
          code: 'WHI',
          name: 'Waiheke Island',
          weatherLocName: 'auckland ',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'AUK',
          code: 'WKC',
          name: 'Waitakere City',
          weatherLocName: 'waitakere',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WKO',
          code: 'HMT',
          name: 'Hamilton',
          weatherLocName: 'hamilton',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WKO',
          code: 'HRK',
          name: 'Hauraki',
          weatherLocName: 'paeroa',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'WKO',
          code: 'MMP',
          name: 'Matamata-Piako',
          weatherLocName: 'matamata',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'WKO',
          code: 'OTH',
          name: 'Otorohanga',
          weatherLocName: 'te-awamutu',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'WKO',
          code: 'SWK',
          name: 'South Waikato',
          weatherLocName: 'tokoroa',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WKO',
          code: 'TUP',
          name: 'Taupo',
          weatherLocName: 'taupo',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WKO',
          code: 'TCD',
          name: 'Thames-Coromandel',
          weatherLocName: 'thames',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WKO',
          code: 'WIK',
          name: 'Waikato',
          weatherLocName: 'hamilton',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WKO',
          code: 'WIP',
          name: 'Waipa',
          weatherLocName: 'te-awamutu',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'WKO',
          code: 'WTM',
          name: 'Waitomo',
          weatherLocName: 'te-awamutu',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'BOP',
          code: 'KWR',
          name: 'Kawerau',
          weatherLocName: 'whakatane',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'BOP',
          code: 'OTK',
          name: 'Opotiki',
          weatherLocName: 'whakatane',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'BOP',
          code: 'RTR',
          name: 'Rotorua',
          weatherLocName: 'rotorua',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'BOP',
          code: 'TRA',
          name: 'Tauranga',
          weatherLocName: 'tauranga',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'BOP',
          code: 'WBP',
          name: 'Western Bay Of Plenty',
          weatherLocName: 'tauranga',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'BOP',
          code: 'WKT',
          name: 'Whakatane',
          weatherLocName: 'whakatane',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'TKI',
          code: 'NPM',
          name: 'New Plymouth',
          weatherLocName: 'new-plymouth',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'TKI',
          code: 'STK',
          name: 'South Taranaki',
          weatherLocName: 'wanganui',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'TKI',
          code: 'STF',
          name: 'Stratford',
          weatherLocName: 'wanganui',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'MWT',
          code: 'HWA',
          name: 'Horowhenua',
          weatherLocName: 'palmerston-north',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'MWT',
          code: 'MWT',
          name: 'Manawatu',
          weatherLocName: 'palmerston-north',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'MWT',
          code: 'PSN',
          name: 'Palmerston North',
          weatherLocName: 'palmerston-north',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'MWT',
          code: 'RTK',
          name: 'Rangitikei',
          weatherLocName: 'waiouru',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'MWT',
          code: 'RPH',
          name: 'Ruapehu',
          weatherLocName: 'waiouru',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'MWT',
          code: 'TRU',
          name: 'Taraua',
          weatherLocName: 'dannevirke',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'MWT',
          code: 'WHN',
          name: 'Whanganui',
          weatherLocName: 'wanganui',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WGN',
          code: 'CTT',
          name: 'Carterton',
          weatherLocName: 'masterton',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'WGN',
          code: 'KTC',
          name: 'Kapiti Coast',
          weatherLocName: 'te-horo',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'WGN',
          code: 'LHT',
          name: 'Lower Hutt',
          weatherLocName: 'lower-hutt',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WGN',
          code: 'MTT',
          name: 'Masterton',
          weatherLocName: 'masterton',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WGN',
          code: 'PRR',
          name: 'Porirua',
          weatherLocName: 'porirua',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WGN',
          code: 'SWP',
          name: 'South Wairarapa',
          weatherLocName: 'martinborough',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'WGN',
          code: 'UHT',
          name: 'Upper Hutt',
          weatherLocName: 'upper-hutt',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WGN',
          code: 'WGT',
          name: 'Wellington',
          weatherLocName: 'wellington',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'NSN',
          code: 'NSN',
          name: 'Nelson',
          weatherLocName: 'nelson',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'NSN',
          code: 'TSM',
          name: 'Tasman',
          weatherLocName: 'motueka',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'MBH',
          code: 'BHM',
          name: 'Blenheim',
          weatherLocName: 'blenheim',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'MBH',
          code: 'KKR',
          name: 'Kaikoura',
          weatherLocName: 'kaikoura',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'MBH',
          code: 'MBR',
          name: 'Marlborough',
          weatherLocName: 'blenheim',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'WTC',
          code: 'BLR',
          name: 'Buller',
          weatherLocName: 'reefton',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WTC',
          code: 'GRY',
          name: 'Grey',
          weatherLocName: 'reefton',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'WTC',
          code: 'WTL',
          name: 'Westland',
          weatherLocName: 'mount-cook',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'CAN',
          code: 'ABT',
          name: 'Ashburton',
          weatherLocName: 'ashburton',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'CAN',
          code: 'BPL',
          name: 'Banks Peninsula',
          weatherLocName: 'banks-peninsula',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'CAN',
          code: 'CCC',
          name: 'Banks Peninsula',
          weatherLocName: 'christchurch',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'CAN',
          code: 'HRN',
          name: 'Hurunui',
          weatherLocName: 'christchurch',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'CAN',
          code: 'MKZ',
          name: 'Mackenzie',
          weatherLocName: 'twizel',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'CAN',
          code: 'SLW',
          name: 'Selwyn',
          weatherLocName: '',
          weatherLocType: '',
        },
        {
          regionCode: 'CAN',
          code: 'TMR',
          name: 'Timaru',
          weatherLocName: '',
          weatherLocType: '',
        },
        {
          regionCode: 'CAN',
          code: 'WKR',
          name: 'Waimakariri',
          weatherLocName: '',
          weatherLocType: '',
        },
        {
          regionCode: 'CAN',
          code: 'WMT',
          name: 'Waimate',
          weatherLocName: 'oamaru',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'OTA',
          code: 'OTG',
          name: 'Central Otago',
          weatherLocName: 'alexandra',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'OTA',
          code: 'CLT',
          name: 'Clutha',
          weatherLocName: 'gore',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'OTA',
          code: 'DND',
          name: 'Dunedin',
          weatherLocName: 'dunedin',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'OTA',
          code: 'QTL',
          name: 'Queenstown-Lakes',
          weatherLocName: 'queenstown',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'OTA',
          code: 'SOT',
          name: 'South Otago',
          weatherLocName: 'alexandra',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'OTA',
          code: 'WNK',
          name: 'Wanaka',
          weatherLocName: 'wanaka',
          weatherLocType: 'urban',
        },
        {
          regionCode: 'STL',
          code: 'CLN',
          name: 'Catlins',
          weatherLocName: 'Gore',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'STL',
          code: 'GRE',
          name: 'Gore',
          weatherLocName: 'Gore',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'STL',
          code: 'ICG',
          name: 'Invercargill',
          weatherLocName: 'Gore',
          weatherLocType: 'rural',
        },
        {
          regionCode: 'STL',
          code: 'STL',
          name: 'Southland',
          weatherLocName: 'Gore',
          weatherLocType: 'rural',
        },
      ])
    })
}
