exports.seed = (knex) => {
  return knex('regions')
    .del()
    .then(() => {
      return knex('regions').insert([
        {
          code: 'AUK',
          ns: 'North',
          name: 'Auckland',
          image: '/images/auckland.jpeg',
          weatherLocName: 'auckland',
          weatherLocType: 'urban',
        },
        {
          code: 'BOP',
          ns: 'North',
          name: 'Bay of Plenty',
          image: '/images/bay-of-island.jpeg',
          weatherLocName: 'te-puke',
          weatherLocType: 'rural',
        },
        {
          code: 'NTL',
          ns: 'North',
          name: 'Northland',
          image: '/images/northland.jpeg',
          weatherLocName: 'whangarei',
          weatherLocType: 'urban',
        },
        {
          code: 'HKB',
          ns: 'North',
          name: "Hawke's Bay",
          image: '/images/hawkes-bay.jpeg',
          weatherLocName: 'hastings',
          weatherLocType: 'urban',
        },
        {
          code: 'GIS',
          ns: 'North',
          name: 'Gisborne',
          image: '/images/gisborne.jpeg',
          weatherLocName: 'gisborne',
          weatherLocType: 'urban',
        },
        {
          code: 'WGN',
          ns: 'North',
          name: 'Wellington',
          image: '/images/wellington.jpeg',
          weatherLocName: 'wellington',
          weatherLocType: 'urban',
        },
        {
          code: 'MWT',
          ns: 'North',
          name: 'Manawatu Whanganui',
          image: '/images/manawatu-whanganui.jpeg',
          weatherLocName: 'wanganui',
          weatherLocType: 'urban',
        },
        {
          code: 'WKO',
          ns: 'North',
          name: 'Waikato',
          image: '/images/waikato.jpeg',
          weatherLocName: 'hamilton',
          weatherLocType: 'urban',
        },
        {
          code: 'TKI',
          ns: 'North',
          name: 'Taranaki',
          image: '/images/taranaki.jpeg',
          weatherLocName: 'wanganui',
          weatherLocType: 'urban',
        },
        {
          code: 'OTA',
          ns: 'South',
          name: 'Otago',
          image: '/images/otago.jpeg',
          weatherLocName: 'alexandra',
          weatherLocType: 'rural',
        },
        {
          code: 'NSN',
          ns: 'South',
          name: 'Nelson',
          image: '/images/nelson.jpeg',
          weatherLocName: 'nelson',
          weatherLocType: 'urban',
        },
        {
          code: 'MBH',
          ns: 'South',
          name: 'Marlborough',
          image: '/images/marlborough.jpeg',
          weatherLocName: 'nelson',
          weatherLocType: 'urban',
        },
        {
          code: 'CAN',
          ns: 'South',
          name: 'Canterbury',
          image: '/images/canterbury.jpeg',
          weatherLocName: 'blenheim',
          weatherLocType: 'rural',
        },
        {
          code: 'WTC',
          ns: 'South',
          name: 'West Coast',
          image: '/images/westcoast.jpeg',
          weatherLocName: 'westport',
          weatherLocType: 'urban',
        },
        {
          code: 'STL',
          ns: 'South',
          name: 'Southland',
          image: '/images/southland.jpeg',
          weatherLocName: 'gore',
          weatherLocType: 'rural',
        },
      ])
    })
}
